version: smartide/v0.2
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: pipeline-task-sample
    webide-port: 6800
    
    ports: # 申明端口
      webide: 6800
      ssh: 6822
      application: 3001
    
    ide-type: vscode  #vscode/theia
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config set registry https://registry.npmmirror.com
      - npm install
  services:
    pipeline-task-sample:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base:latest
      restart: always
    
      volumes:
      - .:/home/project/pipeline-task-sample
      expose:
        - 3000
      ports:
        - 3001:3001
      networks:
        - pipeline-task-sample-network

  networks:
    pipeline-task-sample-network:
      external: true
